### ISSUE TITLE
Numpy should be in the setup requirements

### ISSUE THREAD

**Issue by doctormo** [christopherburke/tess-point#2]
When installing the module for use on tev, the numpy module wasn't automatically pulled in as a dep.

**Comment by christopherburke** [comment]
I am having trouble finding a way to add numpy and astropy as a dependency in setup.py without breaking the ability for people to pip install tess-point under python 2.7.  By including astropy in the install_requires list of setup.py, causes installing tess-point under python 2.7 to fail because astropy requires 3.5+.  Tess-point works just fine under python 2.7 and even though I personally don't recommend using python 2.7, I don't want to break or make python 2.7 users to jump through more hoops.  I have tried using astropy>=2.0.7 to the setup.py, but tess-point still fails to install under python 2.7.  I have tried googling an answer, but I have not found a solution.  Until someone with more knowledge than myself wants to provide a solution for installing under both python 3.5+ and 2.7, I am not going to update the setup requirements at this time.  I agree with you on this issue of explicit requirement is a good thing, but doesn't work yet.

**Comment by christopherburke** [comment]
I gave it one last google foo go, and I found out how to specify python version dependent requirements in setup.py.  This is what I used
    install_requires=[
        'numpy',
        'astropy<=2.0.7;python_version<="2.7"',
        'astropy;python_version>"2.7"',
        'scipy'
    ]
This has been pushed to v0.3.1, so try
pip install tess-point --upgrade
and let me know if this issue can be closed.  Cheers!

**Comment by doctormo** [comment]
This appears to work for me. Thanks for figuring this out, many packages have pledged to remove python3 support, so I guess we all have to get our skates on.

**Comment by christopherburke** [comment]
install_requires=[
'numpy',
'astropy,
'scipy'
]
in the setup.py works just fine by itself.  I was testing the install under python 2.7 incorrectly.  
One needs to use 'pip install -e .' to test the install from the local directory rather than
'python setup.py develop'.
Brigitta Sipocz provided the correct guidance.  Thank you and closing this for good.  Hopefully it will all work out in the end.
